# <span style="color:red; font-size:30px"> Project: Create a Data Structure to hold Voter Information </span>

<font size = "4">

Using the data structures and algorithms we have covered so far, you will implement a custom data structure for managing and analyzing voter data. It will be roughly analagous to a Pandas DataFrame (but you won't need to implement all the functionality that are provided by DataFrames!)

The basic functionality of your data structure can be demonstrated using the Pandas dataframe. In the cell below:

- Some synthetic voter data is generated

- The data is collected in a Pandas DataFrame, where each voter is stored as a single row.

In [25]:
from synthetic_data import *
import pandas as pd

# generate synthetic voter data
data = generate_dataset(n=10)
print(data)
# collect voters as rows
df = pd.DataFrame(data)

display(df)

[{'voter_id': 5570293790, 'age': 85, 'county': 'Cobb', 'party': 'Republican', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1}, {'voter_id': 6762934167, 'age': 74, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1}, {'voter_id': 5237169715, 'age': 89, 'county': 'Clayton', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1}, {'voter_id': 9747886158, 'age': 88, 'county': 'Clayton', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 0}, {'voter_id': 7594867143, 'age': 90, 'county': 'Fulton', 'party': 'Independent', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 0, 't_2022': 1}, {'voter_id': 6119020003, 'age': 34, 'county': 'Gwinnett', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 0, 't_2018': 1, 't_2020': 1, 't_2022': 1}, {'voter_id': 5082115044, 'age': 41, 'county': 'Gwinnett', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 0, 't_2018': 1, 't_2020': 0, 't_2022': 0}, {'voter_id': 7742631005, 'age': 72, 'county': 'Cobb', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 0, 't_2018': 1, 't_2020': 1, 't_2022': 1}, {'voter_id': 8171515310, 'age': 48, 'county': 'Cobb', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 0}, {'voter_id': 5471000753, 'age': 59, 'county': 'Cobb', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 1, 't_2020': 1, 't_2022': 0}]

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
0,5570293790,85,Cobb,Republican,<50K,1,1,1,1
1,6762934167,74,Fulton,Republican,>100K,1,1,1,1
2,5237169715,89,Clayton,Republican,>100K,1,1,1,1
3,9747886158,88,Clayton,Republican,50-100K,1,1,1,0
4,7594867143,90,Fulton,Independent,50-100K,1,1,0,1
5,6119020003,34,Gwinnett,Democrat,<50K,0,1,1,1
6,5082115044,41,Gwinnett,Republican,>100K,0,1,0,0
7,7742631005,72,Cobb,Democrat,<50K,0,1,1,1
8,8171515310,48,Cobb,Republican,50-100K,1,1,1,0
9,5471000753,59,Cobb,Republican,50-100K,0,1,1,0

In [26]:
data[1]

{'voter_id': 6762934167,
 'age': 74,
 'county': 'Fulton',
 'party': 'Republican',
 'income_bracket': '>100K',
 't_2016': 1,
 't_2018': 1,
 't_2020': 1,
 't_2022': 1}

<font size = "4">

- After creating the DataFrame, we may get new data, which can be added to the DataFrame.

In [27]:
# generate new data
new_data = generate_dataset(n=2)

# add it to the DataFrame as new rows
df = pd.concat([df, pd.DataFrame(new_data)], ignore_index=True)

display(df)

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
0,5570293790,85,Cobb,Republican,<50K,1,1,1,1
1,6762934167,74,Fulton,Republican,>100K,1,1,1,1
2,5237169715,89,Clayton,Republican,>100K,1,1,1,1
3,9747886158,88,Clayton,Republican,50-100K,1,1,1,0
4,7594867143,90,Fulton,Independent,50-100K,1,1,0,1
5,6119020003,34,Gwinnett,Democrat,<50K,0,1,1,1
6,5082115044,41,Gwinnett,Republican,>100K,0,1,0,0
7,7742631005,72,Cobb,Democrat,<50K,0,1,1,1
8,8171515310,48,Cobb,Republican,50-100K,1,1,1,0
9,5471000753,59,Cobb,Republican,50-100K,0,1,1,0
10,3111440449,87,Gwinnett,Republican,50-100K,1,1,1,1
11,1649411244,35,Cobb,Democrat,<50K,0,1,1,0

<font size = "4">

- We can sort the rows of the DataFrame by any of the columns:

In [28]:
df.sort_values(by = "voter_id",inplace=True)
display(df)
print()
df.sort_values(by = "county",inplace=True)
display(df)

# ...or any of these other variables
df.sort_values(by = "age", inplace=True)
# df.sort_values(by="party",inplace=True)
# df.sort_values(by="income_bracket",inplace=True)
display(df)
# df.sort_values(by="t_2016",inplace=True)
# df.sort_values(by="t_2018",inplace=True)
# df.sort_values(by="t_2020",inplace=True)
# df.sort_values(by="t_2022",inplace=True)

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
11,1649411244,35,Cobb,Democrat,<50K,0,1,1,0
10,3111440449,87,Gwinnett,Republican,50-100K,1,1,1,1
6,5082115044,41,Gwinnett,Republican,>100K,0,1,0,0
2,5237169715,89,Clayton,Republican,>100K,1,1,1,1
9,5471000753,59,Cobb,Republican,50-100K,0,1,1,0
0,5570293790,85,Cobb,Republican,<50K,1,1,1,1
5,6119020003,34,Gwinnett,Democrat,<50K,0,1,1,1
1,6762934167,74,Fulton,Republican,>100K,1,1,1,1
4,7594867143,90,Fulton,Independent,50-100K,1,1,0,1
7,7742631005,72,Cobb,Democrat,<50K,0,1,1,1
8,8171515310,48,Cobb,Republican,50-100K,1,1,1,0
3,9747886158,88,Clayton,Republican,50-100K,1,1,1,0

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
2,5237169715,89,Clayton,Republican,>100K,1,1,1,1
3,9747886158,88,Clayton,Republican,50-100K,1,1,1,0
11,1649411244,35,Cobb,Democrat,<50K,0,1,1,0
9,5471000753,59,Cobb,Republican,50-100K,0,1,1,0
0,5570293790,85,Cobb,Republican,<50K,1,1,1,1
7,7742631005,72,Cobb,Democrat,<50K,0,1,1,1
8,8171515310,48,Cobb,Republican,50-100K,1,1,1,0
1,6762934167,74,Fulton,Republican,>100K,1,1,1,1
4,7594867143,90,Fulton,Independent,50-100K,1,1,0,1
10,3111440449,87,Gwinnett,Republican,50-100K,1,1,1,1
6,5082115044,41,Gwinnett,Republican,>100K,0,1,0,0
5,6119020003,34,Gwinnett,Democrat,<50K,0,1,1,1

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
5,6119020003,34,Gwinnett,Democrat,<50K,0,1,1,1
11,1649411244,35,Cobb,Democrat,<50K,0,1,1,0
6,5082115044,41,Gwinnett,Republican,>100K,0,1,0,0
8,8171515310,48,Cobb,Republican,50-100K,1,1,1,0
9,5471000753,59,Cobb,Republican,50-100K,0,1,1,0
7,7742631005,72,Cobb,Democrat,<50K,0,1,1,1
1,6762934167,74,Fulton,Republican,>100K,1,1,1,1
0,5570293790,85,Cobb,Republican,<50K,1,1,1,1
10,3111440449,87,Gwinnett,Republican,50-100K,1,1,1,1
3,9747886158,88,Clayton,Republican,50-100K,1,1,1,0
2,5237169715,89,Clayton,Republican,>100K,1,1,1,1
4,7594867143,90,Fulton,Independent,50-100K,1,1,0,1

<font size = "4">

- Even after sorting, we may receive new data. After adding this to the DataFrame, we need to re-sort.

In [29]:
# generate new data
new_data = generate_dataset(n=7)

df = pd.concat([df, pd.DataFrame(new_data)], ignore_index=True)
display(df)
print()
df.sort_values(by = "age",inplace=True)
display(df)

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
0,6119020003,34,Gwinnett,Democrat,<50K,0,1,1,1
1,1649411244,35,Cobb,Democrat,<50K,0,1,1,0
2,5082115044,41,Gwinnett,Republican,>100K,0,1,0,0
3,8171515310,48,Cobb,Republican,50-100K,1,1,1,0
4,5471000753,59,Cobb,Republican,50-100K,0,1,1,0
5,7742631005,72,Cobb,Democrat,<50K,0,1,1,1
6,6762934167,74,Fulton,Republican,>100K,1,1,1,1
7,5570293790,85,Cobb,Republican,<50K,1,1,1,1
8,3111440449,87,Gwinnett,Republican,50-100K,1,1,1,1
9,9747886158,88,Clayton,Republican,50-100K,1,1,1,0
10,5237169715,89,Clayton,Republican,>100K,1,1,1,1
11,7594867143,90,Fulton,Independent,50-100K,1,1,0,1
12,4306599466,42,Clayton,Democrat,<50K,1,0,1,0
13,2845016266,74,Gwinnett,Democrat,>100K,1,1,0,1
14,1906819362,77,Cobb,Democrat,>100K,1,1,1,1
15,2879202240,60,Clayton,Independent,50-100K,1,0,0,0
16,9329453413,63,Gwinnett,Democrat,50-100K,1,1,1,1
17,8472250605,62,DeKalb,Republican,>100K,0,1,1,1
18,8402968367,84,Fulton,Independent,<50K,1,1,1,1

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
0,6119020003,34,Gwinnett,Democrat,<50K,0,1,1,1
1,1649411244,35,Cobb,Democrat,<50K,0,1,1,0
2,5082115044,41,Gwinnett,Republican,>100K,0,1,0,0
12,4306599466,42,Clayton,Democrat,<50K,1,0,1,0
3,8171515310,48,Cobb,Republican,50-100K,1,1,1,0
4,5471000753,59,Cobb,Republican,50-100K,0,1,1,0
15,2879202240,60,Clayton,Independent,50-100K,1,0,0,0
17,8472250605,62,DeKalb,Republican,>100K,0,1,1,1
16,9329453413,63,Gwinnett,Democrat,50-100K,1,1,1,1
5,7742631005,72,Cobb,Democrat,<50K,0,1,1,1
6,6762934167,74,Fulton,Republican,>100K,1,1,1,1
13,2845016266,74,Gwinnett,Democrat,>100K,1,1,0,1
14,1906819362,77,Cobb,Democrat,>100K,1,1,1,1
18,8402968367,84,Fulton,Independent,<50K,1,1,1,1
7,5570293790,85,Cobb,Republican,<50K,1,1,1,1
8,3111440449,87,Gwinnett,Republican,50-100K,1,1,1,1
9,9747886158,88,Clayton,Republican,50-100K,1,1,1,0
10,5237169715,89,Clayton,Republican,>100K,1,1,1,1
11,7594867143,90,Fulton,Independent,50-100K,1,1,0,1

<font size = "4">

- We can sort by a value that does not explicitly appear as a column, but is defined by the data in each row:

In [30]:
# create temporary column
df["turnout_rate"] = df[["t_2016", "t_2018", "t_2020", "t_2022"]].sum(axis = 1) / 4

# sort by the temporary column
df.sort_values(by="turnout_rate",inplace=True)

# drop the temporary column
df.drop(columns="turnout_rate",inplace=True)
df

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
2,5082115044,41,Gwinnett,Republican,>100K,0,1,0,0
15,2879202240,60,Clayton,Independent,50-100K,1,0,0,0
1,1649411244,35,Cobb,Democrat,<50K,0,1,1,0
12,4306599466,42,Clayton,Democrat,<50K,1,0,1,0
4,5471000753,59,Cobb,Republican,50-100K,0,1,1,0
0,6119020003,34,Gwinnett,Democrat,<50K,0,1,1,1
9,9747886158,88,Clayton,Republican,50-100K,1,1,1,0
13,2845016266,74,Gwinnett,Democrat,>100K,1,1,0,1
5,7742631005,72,Cobb,Democrat,<50K,0,1,1,1
17,8472250605,62,DeKalb,Republican,>100K,0,1,1,1
3,8171515310,48,Cobb,Republican,50-100K,1,1,1,0
11,7594867143,90,Fulton,Independent,50-100K,1,1,0,1
10,5237169715,89,Clayton,Republican,>100K,1,1,1,1
6,6762934167,74,Fulton,Republican,>100K,1,1,1,1
14,1906819362,77,Cobb,Democrat,>100K,1,1,1,1
18,8402968367,84,Fulton,Independent,<50K,1,1,1,1
7,5570293790,85,Cobb,Republican,<50K,1,1,1,1
8,3111440449,87,Gwinnett,Republican,50-100K,1,1,1,1
16,9329453413,63,Gwinnett,Democrat,50-100K,1,1,1,1

<font size = "4">

- We can search for items in the DataFrame based on some condition:

In [31]:
# indices corresponding to voters older than 30
print("Indices corresponding to voters older than 30:")
print(df[df["age"] > 30].index.to_list())
print()
print("Indices corresponding to Fulton county voters:")
print(df[df["county"] == "Fulton"].index.to_list())

Indices corresponding to voters older than 30:
[2, 15, 1, 12, 4, 0, 9, 13, 5, 17, 3, 11, 10, 6, 14, 18, 7, 8, 16]

Indices corresponding to Fulton county voters:
[11, 6, 18]

# <span style="color:red; font-size:30px"> Your Task </span>

<font size = "4">

- Instead of storing the data as rows in a Pandas DataFrame, you will implement your own data structure, a *VoterRegistry* class. 

- Instead of storing data in rows, a VoterRegistry stores multiple Voter objects, which is implemented in the next cell.

In [32]:
class Voter:
    def __init__(self, voter_id, age, county, party, income_bracket, turnout_history):
        self.voter_id = voter_id
        self.age = age
        self.county = county
        self.party = party
        self.income_bracket = income_bracket
        self.turnout_history = turnout_history  # list of 0/1

    def turnout_rate(self):
        if not self.turnout_history:
            return 0.0
        return sum(self.turnout_history) / len(self.turnout_history)

    def __repr__(self):
        return (
            f"Voter(id={self.voter_id}, age={self.age}, "
            f"county='{self.county}', party='{self.party}', "
            f"income='{self.income_bracket}')"
        )

# Example use for one data point from a generated dataset
data = generate_dataset(n=100)
single_data_pt = data[0]
turn_out = [single_data_pt["t_2016"], single_data_pt["t_2018"],
    single_data_pt["t_2020"], single_data_pt["t_2022"]]

voter = Voter(single_data_pt["voter_id"],
            single_data_pt["age"],
            single_data_pt["county"],
            single_data_pt["party"],
            single_data_pt["income_bracket"],
            turn_out)

print(voter)
print(voter.turnout_rate())

Voter(id=9397565837, age=50, county='Gwinnett', party='Republican', income='>100K')
0.75

<font size = "4">

- Your VoterRegistry structure must store the Voter objects as either:

    - A collection of linked Nodes. (You may make any edits to the Node class you deem necessary).

    - A Hash Table. For simplicity, you are allowed to use Python lists here, but the index location must be determined by a hash function. 
    
- If you choose to implement a Hash Table, keep the following in mind:

    - We want to be able to add additional Voter objects when new data is generated, so the length of the Python list may need to be dynamically adjusted.

    - To resolve hash collisions, you can use rehashing or you can try chaining using a linked Node structure.

    - We can't "sort" a Hash Table, but you can sort a **view** of a Hash Table (a temporary contiguous array).

- Your VoterRegistry should perform the same basic tasks that we saw with the Pandas DataFrames above:

    - It can be initialized from the output of `generate_dataset`.

    - It can be sorted in ascending order by "voter_id", "age", "county", "party", "income_bracket" and the turnout for the years 2016, 2018, 2020, 2022.

    - It can be sorted in ascending order by the turnout rate. Note that this isn't an attribute of a Voter object, but can be calculated using the `turnout_rate` method.

    - New voter data can be added/appended to the VoterRegistry.

    - We can search for indices/locations corresponding to conditions based on the Voter attributes and standard Boolean comparison operators.

- Perform benchmarking, testing your searching and sorting methods. Try varying the size of the stored data and whether the data is already "almost" sorted or sorted in the opposite order. Summarize your results.

- To make your code and write-up as readable as possible, please include Markdown text describing your implementation decisions and what each object/method/function does.

# <span style="color:red; font-size:30px"> Rubric </span>

1. **Data Structure Design & Implementation (4 points)**: Correctly implements the required data structure (e.g., linked list or hash table), with well-defined classes and attributes that support all require voter fields.

2. **Data Addition & Storage (4 points)**: Successfully adds new voter records, maintains data integrity, and supports dynamic updates (e.g., appending and re-sorting)

3. **Sorting Functionality (4 points)**: Correctly sorts by any required "column" (attribute) and by the computed value of turnout rate.

4. **Search Functionality (3 points)**: Implements search by voter attributes and supports Boolean conditions.

5. **Testing, Demonstration, & Benchmarking (3 points)**: Demonstrates all features with clearly shown examples (e.g., different dataset sizes, re-sorting after additions) and includes benchmarking or performance discussion.

6. **Code Quality & Documentation (2 points)**: Code is clean, readable, well-organized, and clearly documented with Markdown explanations of design decisions.