# <span style="color:red; font-size:30px"> Project: Create a Data Structure to hold Voter Information </span>

<font size = "4">

Using the data structures and algorithms we have covered so far, you will implement a custom data structure for managing and analyzing voter data. It will be roughly analagous to a Pandas DataFrame (but you won't need to implement all the functionality that are provided by DataFrames!)

The basic functionality of your data structure can be demonstrated using the Pandas dataframe. In the cell below:

- Some synthetic voter data is generated

- The data is collected in a Pandas DataFrame, where each voter is stored as a single row.

In [1]:
from synthetic_data import *
import pandas as pd

# generate synthetic voter data
data = generate_dataset(n=10)
print(data)
# collect voters as rows
df = pd.DataFrame(data)

display(df)

[{'voter_id': 4635168894, 'age': 48, 'county': 'Cobb', 'party': 'Democrat', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1}, {'voter_id': 3117761756, 'age': 23, 'county': 'Gwinnett', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 0, 't_2020': 0, 't_2022': 0}, {'voter_id': 2863112530, 'age': 71, 'county': 'Cobb', 'party': 'Independent', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 0, 't_2022': 1}, {'voter_id': 7186863601, 'age': 18, 'county': 'Clayton', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 0, 't_2018': 1, 't_2020': 0, 't_2022': 1}, {'voter_id': 6711630797, 'age': 58, 'county': 'DeKalb', 'party': 'Republican', 'income_bracket': '<50K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 0}, {'voter_id': 1585825032, 'age': 40, 'county': 'DeKalb', 'party': 'Democrat', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1}, {'voter_id': 1604888589, 'age': 81, 'county': 'Cobb', 'party': 'Republican', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1}, {'voter_id': 6323485913, 'age': 82, 'county': 'Fulton', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1}, {'voter_id': 9326311831, 'age': 57, 'county': 'Clayton', 'party': 'Independent', 'income_bracket': '>100K', 't_2016': 1, 't_2018': 0, 't_2020': 0, 't_2022': 1}, {'voter_id': 7297805582, 'age': 88, 'county': 'DeKalb', 'party': 'Republican', 'income_bracket': '50-100K', 't_2016': 1, 't_2018': 1, 't_2020': 1, 't_2022': 1}]

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
0,4635168894,48,Cobb,Democrat,<50K,1,1,1,1
1,3117761756,23,Gwinnett,Democrat,50-100K,0,0,0,0
2,2863112530,71,Cobb,Independent,<50K,1,1,0,1
3,7186863601,18,Clayton,Republican,50-100K,0,1,0,1
4,6711630797,58,DeKalb,Republican,<50K,1,1,1,0
5,1585825032,40,DeKalb,Democrat,50-100K,1,1,1,1
6,1604888589,81,Cobb,Republican,>100K,1,1,1,1
7,6323485913,82,Fulton,Republican,50-100K,1,1,1,1
8,9326311831,57,Clayton,Independent,>100K,1,0,0,1
9,7297805582,88,DeKalb,Republican,50-100K,1,1,1,1

In [2]:
data[1]

{'voter_id': 3117761756,
 'age': 23,
 'county': 'Gwinnett',
 'party': 'Democrat',
 'income_bracket': '50-100K',
 't_2016': 0,
 't_2018': 0,
 't_2020': 0,
 't_2022': 0}

<font size = "4">

- After creating the DataFrame, we may get new data, which can be added to the DataFrame.

In [3]:
# generate new data
new_data = generate_dataset(n=2)

# add it to the DataFrame as new rows
df = pd.concat([df, pd.DataFrame(new_data)], ignore_index=True)

display(df)

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
0,4635168894,48,Cobb,Democrat,<50K,1,1,1,1
1,3117761756,23,Gwinnett,Democrat,50-100K,0,0,0,0
2,2863112530,71,Cobb,Independent,<50K,1,1,0,1
3,7186863601,18,Clayton,Republican,50-100K,0,1,0,1
4,6711630797,58,DeKalb,Republican,<50K,1,1,1,0
5,1585825032,40,DeKalb,Democrat,50-100K,1,1,1,1
6,1604888589,81,Cobb,Republican,>100K,1,1,1,1
7,6323485913,82,Fulton,Republican,50-100K,1,1,1,1
8,9326311831,57,Clayton,Independent,>100K,1,0,0,1
9,7297805582,88,DeKalb,Republican,50-100K,1,1,1,1
10,7412080025,74,Clayton,Democrat,50-100K,1,0,1,1
11,3864826756,79,DeKalb,Democrat,<50K,1,1,1,1

<font size = "4">

- We can sort the rows of the DataFrame by any of the columns:

In [4]:
df.sort_values(by = "voter_id",inplace=True)
display(df)
print()
df.sort_values(by = "county",inplace=True)
display(df)

# ...or any of these other variables
df.sort_values(by = "age", inplace=True)
# df.sort_values(by="party",inplace=True)
# df.sort_values(by="income_bracket",inplace=True)
display(df)
# df.sort_values(by="t_2016",inplace=True)
# df.sort_values(by="t_2018",inplace=True)
# df.sort_values(by="t_2020",inplace=True)
# df.sort_values(by="t_2022",inplace=True)

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
5,1585825032,40,DeKalb,Democrat,50-100K,1,1,1,1
6,1604888589,81,Cobb,Republican,>100K,1,1,1,1
2,2863112530,71,Cobb,Independent,<50K,1,1,0,1
1,3117761756,23,Gwinnett,Democrat,50-100K,0,0,0,0
11,3864826756,79,DeKalb,Democrat,<50K,1,1,1,1
0,4635168894,48,Cobb,Democrat,<50K,1,1,1,1
7,6323485913,82,Fulton,Republican,50-100K,1,1,1,1
4,6711630797,58,DeKalb,Republican,<50K,1,1,1,0
3,7186863601,18,Clayton,Republican,50-100K,0,1,0,1
9,7297805582,88,DeKalb,Republican,50-100K,1,1,1,1
10,7412080025,74,Clayton,Democrat,50-100K,1,0,1,1
8,9326311831,57,Clayton,Independent,>100K,1,0,0,1

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
3,7186863601,18,Clayton,Republican,50-100K,0,1,0,1
10,7412080025,74,Clayton,Democrat,50-100K,1,0,1,1
8,9326311831,57,Clayton,Independent,>100K,1,0,0,1
6,1604888589,81,Cobb,Republican,>100K,1,1,1,1
2,2863112530,71,Cobb,Independent,<50K,1,1,0,1
0,4635168894,48,Cobb,Democrat,<50K,1,1,1,1
5,1585825032,40,DeKalb,Democrat,50-100K,1,1,1,1
11,3864826756,79,DeKalb,Democrat,<50K,1,1,1,1
4,6711630797,58,DeKalb,Republican,<50K,1,1,1,0
9,7297805582,88,DeKalb,Republican,50-100K,1,1,1,1
7,6323485913,82,Fulton,Republican,50-100K,1,1,1,1
1,3117761756,23,Gwinnett,Democrat,50-100K,0,0,0,0

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
3,7186863601,18,Clayton,Republican,50-100K,0,1,0,1
1,3117761756,23,Gwinnett,Democrat,50-100K,0,0,0,0
5,1585825032,40,DeKalb,Democrat,50-100K,1,1,1,1
0,4635168894,48,Cobb,Democrat,<50K,1,1,1,1
8,9326311831,57,Clayton,Independent,>100K,1,0,0,1
4,6711630797,58,DeKalb,Republican,<50K,1,1,1,0
2,2863112530,71,Cobb,Independent,<50K,1,1,0,1
10,7412080025,74,Clayton,Democrat,50-100K,1,0,1,1
11,3864826756,79,DeKalb,Democrat,<50K,1,1,1,1
6,1604888589,81,Cobb,Republican,>100K,1,1,1,1
7,6323485913,82,Fulton,Republican,50-100K,1,1,1,1
9,7297805582,88,DeKalb,Republican,50-100K,1,1,1,1

<font size = "4">

- Even after sorting, we may receive new data. After adding this to the DataFrame, we need to re-sort.

In [5]:
# generate new data
new_data = generate_dataset(n=7)

df = pd.concat([df, pd.DataFrame(new_data)], ignore_index=True)
display(df)
print()
df.sort_values(by = "age",inplace=True)
display(df)

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
0,7186863601,18,Clayton,Republican,50-100K,0,1,0,1
1,3117761756,23,Gwinnett,Democrat,50-100K,0,0,0,0
2,1585825032,40,DeKalb,Democrat,50-100K,1,1,1,1
3,4635168894,48,Cobb,Democrat,<50K,1,1,1,1
4,9326311831,57,Clayton,Independent,>100K,1,0,0,1
5,6711630797,58,DeKalb,Republican,<50K,1,1,1,0
6,2863112530,71,Cobb,Independent,<50K,1,1,0,1
7,7412080025,74,Clayton,Democrat,50-100K,1,0,1,1
8,3864826756,79,DeKalb,Democrat,<50K,1,1,1,1
9,1604888589,81,Cobb,Republican,>100K,1,1,1,1
10,6323485913,82,Fulton,Republican,50-100K,1,1,1,1
11,7297805582,88,DeKalb,Republican,50-100K,1,1,1,1
12,4190820770,75,Cobb,Independent,50-100K,1,1,1,1
13,3586629988,54,Clayton,Democrat,50-100K,1,0,1,1
14,1341439452,67,Gwinnett,Independent,50-100K,1,1,1,0
15,8253390367,82,DeKalb,Democrat,50-100K,1,1,0,1
16,1681184466,24,Clayton,Independent,50-100K,0,1,1,0
17,7958010112,62,Gwinnett,Republican,<50K,1,0,1,1
18,4579646493,53,Cobb,Democrat,>100K,1,1,1,1

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
0,7186863601,18,Clayton,Republican,50-100K,0,1,0,1
1,3117761756,23,Gwinnett,Democrat,50-100K,0,0,0,0
16,1681184466,24,Clayton,Independent,50-100K,0,1,1,0
2,1585825032,40,DeKalb,Democrat,50-100K,1,1,1,1
3,4635168894,48,Cobb,Democrat,<50K,1,1,1,1
18,4579646493,53,Cobb,Democrat,>100K,1,1,1,1
13,3586629988,54,Clayton,Democrat,50-100K,1,0,1,1
4,9326311831,57,Clayton,Independent,>100K,1,0,0,1
5,6711630797,58,DeKalb,Republican,<50K,1,1,1,0
17,7958010112,62,Gwinnett,Republican,<50K,1,0,1,1
14,1341439452,67,Gwinnett,Independent,50-100K,1,1,1,0
6,2863112530,71,Cobb,Independent,<50K,1,1,0,1
7,7412080025,74,Clayton,Democrat,50-100K,1,0,1,1
12,4190820770,75,Cobb,Independent,50-100K,1,1,1,1
8,3864826756,79,DeKalb,Democrat,<50K,1,1,1,1
9,1604888589,81,Cobb,Republican,>100K,1,1,1,1
10,6323485913,82,Fulton,Republican,50-100K,1,1,1,1
15,8253390367,82,DeKalb,Democrat,50-100K,1,1,0,1
11,7297805582,88,DeKalb,Republican,50-100K,1,1,1,1

<font size = "4">

- We can sort by a value that does not explicitly appear as a column, but is defined by the data in each row:

In [6]:
# create temporary column
df["turnout_rate"] = df[["t_2016", "t_2018", "t_2020", "t_2022"]].sum(axis = 1) / 4

# sort by the temporary column
df.sort_values(by="turnout_rate",inplace=True)

# drop the temporary column
df.drop(columns="turnout_rate",inplace=True)
df

,voter_id,age,county,party,income_bracket,t_2016,t_2018,t_2020,t_2022
1,3117761756,23,Gwinnett,Democrat,50-100K,0,0,0,0
0,7186863601,18,Clayton,Republican,50-100K,0,1,0,1
16,1681184466,24,Clayton,Independent,50-100K,0,1,1,0
4,9326311831,57,Clayton,Independent,>100K,1,0,0,1
7,7412080025,74,Clayton,Democrat,50-100K,1,0,1,1
6,2863112530,71,Cobb,Independent,<50K,1,1,0,1
14,1341439452,67,Gwinnett,Independent,50-100K,1,1,1,0
15,8253390367,82,DeKalb,Democrat,50-100K,1,1,0,1
17,7958010112,62,Gwinnett,Republican,<50K,1,0,1,1
13,3586629988,54,Clayton,Democrat,50-100K,1,0,1,1
5,6711630797,58,DeKalb,Republican,<50K,1,1,1,0
18,4579646493,53,Cobb,Democrat,>100K,1,1,1,1
3,4635168894,48,Cobb,Democrat,<50K,1,1,1,1
2,1585825032,40,DeKalb,Democrat,50-100K,1,1,1,1
12,4190820770,75,Cobb,Independent,50-100K,1,1,1,1
8,3864826756,79,DeKalb,Democrat,<50K,1,1,1,1
9,1604888589,81,Cobb,Republican,>100K,1,1,1,1
10,6323485913,82,Fulton,Republican,50-100K,1,1,1,1
11,7297805582,88,DeKalb,Republican,50-100K,1,1,1,1

<font size = "4">

- We can search for items in the DataFrame based on some condition:

In [7]:
# indices corresponding to voters older than 30
print("Indices corresponding to voters older than 30:")
print(df[df["age"] > 30].index.to_list())
print()
print("Indices corresponding to Fulton county voters:")
print(df[df["county"] == "Fulton"].index.to_list())

Indices corresponding to voters older than 30:
[4, 7, 6, 14, 15, 17, 13, 5, 18, 3, 2, 12, 8, 9, 10, 11]

Indices corresponding to Fulton county voters:
[10]

# <span style="color:red; font-size:30px"> Your Task </span>

<font size = "4">

- Instead of storing the data as rows in a Pandas DataFrame, you will implement your own data structure, a *VoterRegistry* class. 

- Instead of storing data in rows, a VoterRegistry stores multiple Voter objects, which is implemented in the next cell.

In [10]:
class Voter:
    def __init__(self, voter_id, age, county, party, income_bracket, turnout_history):
        self.voter_id = voter_id
        self.age = age
        self.county = county
        self.party = party
        self.income_bracket = income_bracket
        self.turnout_history = turnout_history  # list of 0/1

    def turnout_rate(self):
        if not self.turnout_history:
            return 0.0
        return sum(self.turnout_history) / len(self.turnout_history)

    def __repr__(self):
        return (
            f"Voter(id={self.voter_id}, age={self.age}, "
            f"county='{self.county}', party='{self.party}', "
            f"income='{self.income_bracket}')"
        )

# Example use for one data point from a generated dataset
data = generate_dataset(n=100)
single_data_pt = data[0]
turn_out = [single_data_pt["t_2016"], single_data_pt["t_2018"],
    single_data_pt["t_2020"], single_data_pt["t_2022"]]

voter = Voter(single_data_pt["voter_id"],
            single_data_pt["age"],
            single_data_pt["county"],
            single_data_pt["party"],
            single_data_pt["income_bracket"],
            turn_out)

print(voter)
print(voter.turnout_rate())

Voter(id=6378767053, age=75, county='Clayton', party='Independent', income='50-100K')
1.0

## Implementation: VoterRegistry

<font size = "4">

### Data Structure Choice
I implemented `VoterRegistry` using a linked list, where each `Node` stores one `Voter` object and a pointer to the next node. This design was chosen for its simplicity: O(1) insertion at the head and no hash collision handling required.

<font size = "4">

### `Node`
A class that stores `Voter` object and a `next` pointer to the following node.

In [ ]:
class Node:
    def __init__(self, voter):
        self.voter = voter
        self.next = None

<font size = "4">

### `VoterRegistry`
It stores all `Voter` objects in a linked list, where each `Voter` is wrapped in a `Node` and connected to the next one via a pointer. Below I will introduce the function within the class and how they enable sorting and searching.

- `dict_to_voter()`: Converts a dictionary from `generate_dataset()` into a `Voter` object, and package the four turnout fields into a list.

- `add()`: Inserts a new `Voter` at the head of the list by creating a new `Node`, pointing its next to the current head, then updating the head to the new node.

- `conv_to_list()`: Traverses the linked list, collecting each `Voter` object into a Python list. And this function is called within the class to enable sorting operations.

- `conv_from_list()`: Rebuilds the linked list from a sorted list.

- `sort()`: Sorts the registry by any voter attribute using merge sort (O(n log n)). Converts to list, sorts, rebuilds linked list.

- `search()`: Traverses the list and returns `(index, Voter)` pairs for all voters based on the given condition.

- `__repr__()`: Defines how the registry is displayed when printed. Each voter is shown with their attributes and `turnout_rate`, since `turnout_rate` is not stored as a field but we need it to visually verify that sorting by `turnout_rate` is correct.

#### `income_bracket` Ordering
`income_bracket` is a categorical string. To sort it by actual income order rather than alphabetical order, it is mapped to integers: 
- "<50K"→0
-"50-100K"→1
-">100K"→2


#### Sorting: Merge Sort
Merge sort was chosen because it works on lists and has O(n log n) performance.

In [ ]:
class VoterRegistry:
    def __init__(self, data):
        self.head = None
        self.size = 0
        if data:
            for d in data:
                self.add(self.dict_to_voter(d))
    def dict_to_voter(self, d):
        turnout_history = [d["t_2016"], d["t_2018"], d["t_2020"], d["t_2022"]]
        return Voter(d["voter_id"], d["age"], d["county"], d["party"], d["income_bracket"], turnout_history)
    
    def add(self, voter):
        temp = Node(voter)
        temp.next = self.head 
        self.head = temp
        self.size += 1
    
    def conv_to_list(self):
        result = []
        current = self.head
        while current:
            result.append(current.voter)
            current = current.next
        return result
    
    def conv_from_list(self, voters):
        self.head = None
        self.size = 0
        for v in voters:
            self.add(v)
    
    def sort(self, indice):
         voters = self.conv_to_list()
         sorted_voters = self.merge_sort(voters, indice)
         self.conv_from_list(sorted_voters)

    var_dict = {
        "voter_id": lambda v: v.voter_id,
        "age": lambda v: v.age,
        "county": lambda v: v.county,
        "party": lambda v: v.party,
        "income_bracket": lambda v: {"<50K": 0, "50-100K": 1, ">100K": 2}[v.income_bracket],
        "t_2016": lambda v: v.turnout_history[0],
        "t_2018": lambda v: v.turnout_history[1],
        "t_2020": lambda v: v.turnout_history[2],
        "t_2022": lambda v: v.turnout_history[3],
        "turnout_rate": lambda v: v.turnout_rate(),
    }

    def merge_sort(self, lst, indice):
        if len(lst) <= 1:
            return lst

        mid = len(lst) // 2
        left_half = lst[:mid]
        right_half = lst[mid:]

        # recursive call to each half
        left_half = self.merge_sort(left_half, indice)
        right_half = self.merge_sort(right_half, indice)
        
        ind = self.var_dict[indice]
        i, j, k = 0, 0, 0
        while i < len(left_half) and j < len(right_half):
            if ind(left_half[i]) <= ind(right_half[j]):
                lst[k] = left_half[i]
                i = i + 1
            else:
                lst[k] = right_half[j]
                j = j + 1
            k = k + 1

        while i < len(left_half):
            lst[k] = left_half[i]
            i = i + 1
            k = k + 1

        while j < len(right_half):
            lst[k] = right_half[j]
            j = j + 1
            k = k + 1
        return lst
    
    def search(self, condition):
        results = []
        current = self.head
        index = 0
        while current is not None:
            if condition(current.voter):
                results.append((index, current.voter))
            current = current.next
            index += 1
        return results

    def __repr__(self):
        lines = [f"VoterRegistry ({self.size} voters)"]
        for i, v in enumerate(self.conv_to_list()):
            lines.append(f" [{i}] {v} | turnout_rate={v.turnout_rate()}")
        return "\n".join(lines)

<font size = "4">

#### Test

- n = 5

- sort by `age`

- search by `county`

In [46]:
# test n=5
data = generate_dataset(n = 5)
reg1 = VoterRegistry(data)
print(reg1)

reg1.sort("age")
print(reg1)

results = reg1.search(lambda v: v.county == "DeKalb")
print(results)

VoterRegistry (5 voters)
 [0] Voter(id=9188507403, age=59, county='Fulton', party='Democrat', income='50-100K') | turnout_rate=1.0
 [1] Voter(id=7597127006, age=57, county='Cobb', party='Republican', income='50-100K') | turnout_rate=0.75
 [2] Voter(id=3011920634, age=37, county='Fulton', party='Independent', income='50-100K') | turnout_rate=0.75
 [3] Voter(id=7168895498, age=46, county='Clayton', party='Democrat', income='50-100K') | turnout_rate=0.5
 [4] Voter(id=6829539974, age=90, county='Clayton', party='Democrat', income='50-100K') | turnout_rate=1.0
VoterRegistry (5 voters)
 [0] Voter(id=6829539974, age=90, county='Clayton', party='Democrat', income='50-100K') | turnout_rate=1.0
 [1] Voter(id=9188507403, age=59, county='Fulton', party='Democrat', income='50-100K') | turnout_rate=1.0
 [2] Voter(id=7597127006, age=57, county='Cobb', party='Republican', income='50-100K') | turnout_rate=0.75
 [3] Voter(id=7168895498, age=46, county='Clayton', party='Democrat', income='50-100K') | turnout_rate=0.5
 [4] Voter(id=3011920634, age=37, county='Fulton', party='Independent', income='50-100K') | turnout_rate=0.75
[]

<font size = "4">

#### Test

- n = 10

- sort by `voter_id`

- sort by `turnout_rate`

- add new data

- sort by `turnout_rate`

- sort by `income_bracket`

- search by `age`

In [47]:
# test, n=10
data = generate_dataset(n=10)
reg2 = VoterRegistry(data)
print(reg2)

reg2.sort("voter_id")
print(reg2)

VoterRegistry (10 voters)
 [0] Voter(id=2158418130, age=58, county='Fulton', party='Republican', income='<50K') | turnout_rate=0.25
 [1] Voter(id=8578293312, age=22, county='Clayton', party='Democrat', income='<50K') | turnout_rate=0.75
 [2] Voter(id=1328334503, age=61, county='Gwinnett', party='Republican', income='<50K') | turnout_rate=0.5
 [3] Voter(id=9942450243, age=83, county='Fulton', party='Republican', income='<50K') | turnout_rate=1.0
 [4] Voter(id=7273654046, age=51, county='Cobb', party='Republican', income='<50K') | turnout_rate=0.75
 [5] Voter(id=1831556090, age=20, county='Fulton', party='Republican', income='<50K') | turnout_rate=0.75
 [6] Voter(id=7489335410, age=62, county='Fulton', party='Republican', income='>100K') | turnout_rate=1.0
 [7] Voter(id=2644753112, age=83, county='Fulton', party='Independent', income='50-100K') | turnout_rate=1.0
 [8] Voter(id=9253941140, age=51, county='DeKalb', party='Democrat', income='<50K') | turnout_rate=0.75
 [9] Voter(id=8559950369, age=52, county='Clayton', party='Democrat', income='50-100K') | turnout_rate=0.5
VoterRegistry (10 voters)
 [0] Voter(id=9942450243, age=83, county='Fulton', party='Republican', income='<50K') | turnout_rate=1.0
 [1] Voter(id=9253941140, age=51, county='DeKalb', party='Democrat', income='<50K') | turnout_rate=0.75
 [2] Voter(id=8578293312, age=22, county='Clayton', party='Democrat', income='<50K') | turnout_rate=0.75
 [3] Voter(id=8559950369, age=52, county='Clayton', party='Democrat', income='50-100K') | turnout_rate=0.5
 [4] Voter(id=7489335410, age=62, county='Fulton', party='Republican', income='>100K') | turnout_rate=1.0
 [5] Voter(id=7273654046, age=51, county='Cobb', party='Republican', income='<50K') | turnout_rate=0.75
 [6] Voter(id=2644753112, age=83, county='Fulton', party='Independent', income='50-100K') | turnout_rate=1.0
 [7] Voter(id=2158418130, age=58, county='Fulton', party='Republican', income='<50K') | turnout_rate=0.25
 [8] Voter(id=1831556090, age=20, county='Fulton', party='Republican', income='<50K') | turnout_rate=0.75
 [9] Voter(id=1328334503, age=61, county='Gwinnett', party='Republican', income='<50K') | turnout_rate=0.5

In [48]:
reg2.sort("turnout_rate")
print(reg2)

VoterRegistry (10 voters)
 [0] Voter(id=2644753112, age=83, county='Fulton', party='Independent', income='50-100K') | turnout_rate=1.0
 [1] Voter(id=7489335410, age=62, county='Fulton', party='Republican', income='>100K') | turnout_rate=1.0
 [2] Voter(id=9942450243, age=83, county='Fulton', party='Republican', income='<50K') | turnout_rate=1.0
 [3] Voter(id=1831556090, age=20, county='Fulton', party='Republican', income='<50K') | turnout_rate=0.75
 [4] Voter(id=7273654046, age=51, county='Cobb', party='Republican', income='<50K') | turnout_rate=0.75
 [5] Voter(id=8578293312, age=22, county='Clayton', party='Democrat', income='<50K') | turnout_rate=0.75
 [6] Voter(id=9253941140, age=51, county='DeKalb', party='Democrat', income='<50K') | turnout_rate=0.75
 [7] Voter(id=1328334503, age=61, county='Gwinnett', party='Republican', income='<50K') | turnout_rate=0.5
 [8] Voter(id=8559950369, age=52, county='Clayton', party='Democrat', income='50-100K') | turnout_rate=0.5
 [9] Voter(id=2158418130, age=58, county='Fulton', party='Republican', income='<50K') | turnout_rate=0.25

In [53]:
reg2.add(reg2.dict_to_voter(generate_dataset(n=3)[0]))
reg2.sort("income_bracket")
print(reg2)

results = reg2.search(lambda v: v.age > 50)
print(results)

VoterRegistry (13 voters)
 [0] Voter(id=8412570705, age=22, county='DeKalb', party='Republican', income='>100K') | turnout_rate=0.5
 [1] Voter(id=7489335410, age=62, county='Fulton', party='Republican', income='>100K') | turnout_rate=1.0
 [2] Voter(id=8559950369, age=52, county='Clayton', party='Democrat', income='50-100K') | turnout_rate=0.5
 [3] Voter(id=2644753112, age=83, county='Fulton', party='Independent', income='50-100K') | turnout_rate=1.0
 [4] Voter(id=2158418130, age=58, county='Fulton', party='Republican', income='<50K') | turnout_rate=0.25
 [5] Voter(id=1328334503, age=61, county='Gwinnett', party='Republican', income='<50K') | turnout_rate=0.5
 [6] Voter(id=9253941140, age=51, county='DeKalb', party='Democrat', income='<50K') | turnout_rate=0.75
 [7] Voter(id=8578293312, age=22, county='Clayton', party='Democrat', income='<50K') | turnout_rate=0.75
 [8] Voter(id=7273654046, age=51, county='Cobb', party='Republican', income='<50K') | turnout_rate=0.75
 [9] Voter(id=1831556090, age=20, county='Fulton', party='Republican', income='<50K') | turnout_rate=0.75
 [10] Voter(id=9942450243, age=83, county='Fulton', party='Republican', income='<50K') | turnout_rate=1.0
 [11] Voter(id=4416473707, age=24, county='Gwinnett', party='Republican', income='<50K') | turnout_rate=0.5
 [12] Voter(id=3260437874, age=56, county='Gwinnett', party='Republican', income='<50K') | turnout_rate=0.75
[(1, Voter(id=7489335410, age=62, county='Fulton', party='Republican', income='>100K')), (2, Voter(id=8559950369, age=52, county='Clayton', party='Democrat', income='50-100K')), (3, Voter(id=2644753112, age=83, county='Fulton', party='Independent', income='50-100K')), (4, Voter(id=2158418130, age=58, county='Fulton', party='Republican', income='<50K')), (5, Voter(id=1328334503, age=61, county='Gwinnett', party='Republican', income='<50K')), (6, Voter(id=9253941140, age=51, county='DeKalb', party='Democrat', income='<50K')), (8, Voter(id=7273654046, age=51, county='Cobb', party='Republican', income='<50K')), (10, Voter(id=9942450243, age=83, county='Fulton', party='Republican', income='<50K')), (12, Voter(id=3260437874, age=56, county='Gwinnett', party='Republican', income='<50K'))]

<font size = "4">

### Benchmarking

I tested sorting and search performance across data sizes of n = 10, 100, 1000, 10000.

In [51]:
import time

# varying n
for n in [10, 100, 1000, 10000]:
    data = generate_dataset(n=n)
    registry = VoterRegistry(data)

    t0 = time.time()
    registry.sort("voter_id")
    sort_time = time.time() - t0

    t0 = time.time()
    results = registry.search(lambda v: v.age > 50)
    search_time = time.time() - t0

    print(f"n={n} | sort: {sort_time:.6f}s | search: {search_time:.6f}s")

n=10 | sort: 0.001654s | search: 0.008909s
n=100 | sort: 0.002177s | search: 0.000107s
n=1000 | sort: 0.028997s | search: 0.001062s
n=10000 | sort: 0.364179s | search: 0.012595s

<font size = "4">

- Sort time grows roughly as O(n log n): from n=1000 to n=10000 (10x data), sort time increases ~13x.

- Search time grows roughly as O(n): When the data size increases by 10 times, the search time increases by approximately 10.

<font size = "4">

- Your VoterRegistry structure must store the Voter objects as either:

    - A collection of linked Nodes. (You may make any edits to the Node class you deem necessary).

    - A Hash Table. For simplicity, you are allowed to use Python lists here, but the index location must be determined by a hash function. 
    
- If you choose to implement a Hash Table, keep the following in mind:

    - We want to be able to add additional Voter objects when new data is generated, so the length of the Python list may need to be dynamically adjusted.

    - To resolve hash collisions, you can use rehashing or you can try chaining using a linked Node structure.

    - We can't "sort" a Hash Table, but you can sort a **view** of a Hash Table (a temporary contiguous array).

- Your VoterRegistry should perform the same basic tasks that we saw with the Pandas DataFrames above:

    - It can be initialized from the output of `generate_dataset`.

    - It can be sorted in ascending order by "voter_id", "age", "county", "party", "income_bracket" and the turnout for the years 2016, 2018, 2020, 2022.

    - It can be sorted in ascending order by the turnout rate. Note that this isn't an attribute of a Voter object, but can be calculated using the `turnout_rate` method.

    - New voter data can be added/appended to the VoterRegistry.

    - We can search for indices/locations corresponding to conditions based on the Voter attributes and standard Boolean comparison operators.

- Perform benchmarking, testing your searching and sorting methods. Try varying the size of the stored data and whether the data is already "almost" sorted or sorted in the opposite order. Summarize your results.

- To make your code and write-up as readable as possible, please include Markdown text describing your implementation decisions and what each object/method/function does.

# <span style="color:red; font-size:30px"> Rubric </span>

1. **Data Structure Design & Implementation (4 points)**: Correctly implements the required data structure (e.g., linked list or hash table), with well-defined classes and attributes that support all require voter fields.

2. **Data Addition & Storage (4 points)**: Successfully adds new voter records, maintains data integrity, and supports dynamic updates (e.g., appending and re-sorting)

3. **Sorting Functionality (4 points)**: Correctly sorts by any required "column" (attribute) and by the computed value of turnout rate.

4. **Search Functionality (3 points)**: Implements search by voter attributes and supports Boolean conditions.

5. **Testing, Demonstration, & Benchmarking (3 points)**: Demonstrates all features with clearly shown examples (e.g., different dataset sizes, re-sorting after additions) and includes benchmarking or performance discussion.

6. **Code Quality & Documentation (2 points)**: Code is clean, readable, well-organized, and clearly documented with Markdown explanations of design decisions.